/**
 * Generator Component
 * 
 * Main architecture generation interface.
 * Uses shared state from App component via Outlet context.
 * Now with async polling for long-running generation tasks.
 */

import React, { useState, useEffect } from 'react'
import { useOutletContext } from 'react-router-dom'
import { InputPanel } from '../components/InputPanel'
import { LoadingSpinner } from '../components/LoadingSpinner'
import { ErrorAlert } from '../components/ErrorAlert'
import { OutputPanel } from '../components/OutputPanel'
import { startGeneration, getGenerationStatus } from '../services/api'

interface GeneratorContext {
  requirements: string
  setRequirements: (value: string) => void
  isGenerating: boolean
  setIsGenerating: (value: boolean) => void
  error: string | null
  setError: (value: string | null) => void
  architectureData: any
  setArchitectureData: (value: any) => void
}

const Generator: React.FC = () => {
  const {
    requirements,
    setRequirements,
    isGenerating,
    setIsGenerating,
    error,
    setError,
    architectureData,
    setArchitectureData
  } = useOutletContext<GeneratorContext>()
  
  const [progress, setProgress] = useState(0)
  const [progressMessage, setProgressMessage] = useState('')
  const [currentTaskId, setCurrentTaskId] = useState<string | null>(null)

  // Poll for task status
  useEffect(() => {
    if (!currentTaskId || !isGenerating) {
      return
    }

    const pollInterval = setInterval(async () => {
      try {
        const status = await getGenerationStatus(currentTaskId)
        
        setProgress(status.progress)
        setProgressMessage(status.message)
        
        if (status.status === 'completed' && status.data) {
          setArchitectureData(status.data)
          setIsGenerating(false)
          setCurrentTaskId(null)
          clearInterval(pollInterval)
        } else if (status.status === 'failed') {
          setError(status.error || 'Generation failed')
          setIsGenerating(false)
          setCurrentTaskId(null)
          clearInterval(pollInterval)
        }
      } catch (err) {
        console.error('Failed to poll task status:', err)
        setError('Failed to check generation status')
        setIsGenerating(false)
        setCurrentTaskId(null)
        clearInterval(pollInterval)
      }
    }, 2000) // Poll every 2 seconds

    return () => clearInterval(pollInterval)
  }, [currentTaskId, isGenerating, setArchitectureData, setError, setIsGenerating])

  const handleGenerate = async () => {
    if (!requirements.trim()) {
      setError('Please enter your AWS architecture requirements')
      return
    }

    setIsGenerating(true)
    setError(null)
    setArchitectureData(null)
    setProgress(0)
    setProgressMessage('Starting generation...')

    try {
      // Start generation
      const response = await startGeneration(requirements)
      setCurrentTaskId(response.task_id)
      setProgressMessage(response.message)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An unexpected error occurred')
      setIsGenerating(false)
    }
  }

  return (
    <div className="space-y-8">
      {/* Page Header */}
      <div className="text-center">
        <h1 className="text-4xl font-bold text-slate-100 mb-4">
          AWS Architecture Generator
        </h1>
        <p className="text-slate-400 max-w-2xl mx-auto">
          Describe your AWS infrastructure requirements and get a complete CloudFormation template, 
          architecture diagram, and cost estimate generated by AI agents.
        </p>
      </div>

      {/* Input Panel */}
      <InputPanel
        requirements={requirements}
        setRequirements={setRequirements}
        onSubmit={(e) => {
          e.preventDefault()
          handleGenerate()
        }}
        loading={isGenerating}
      />

      {/* Loading State with Progress */}
      {isGenerating && (
        <div className="bg-slate-800 border border-slate-700 rounded-lg p-8">
          <div className="text-center space-y-4">
            <LoadingSpinner />
            <div className="space-y-2">
              <div className="text-lg font-medium text-slate-200">{progressMessage}</div>
              <div className="w-full bg-slate-700 rounded-full h-2.5">
                <div 
                  className="bg-blue-600 h-2.5 rounded-full transition-all duration-500"
                  style={{ width: `${progress}%` }}
                ></div>
              </div>
              <div className="text-sm text-slate-400">{progress}% complete</div>
            </div>
          </div>
        </div>
      )}

      {/* Error State */}
      {error && <ErrorAlert error={error} onDismiss={() => setError(null)} />}

      {/* Results */}
      {architectureData && !isGenerating && (
        <OutputPanel data={architectureData} />
      )}
    </div>
  )
}

export default Generator
